### ISSUE TITLE
feat: complimentaryColor() should convert hex into it's complementary hex color code

### ISSUE THREAD

**Issue by AnshSinghSonkhia** [AnshSinghSonkhia/random-math#2]
`complimentaryColor()` should convert hex into it's complementary hex color code.

## Currently, it is working like this:

```js
console.log(Random.complimentaryColor("rgb(100,200,250)"));
// returns - rgb(250,150,100)

console.log(Random.complimentaryColor("hsl(120,50%,50%)"));
// returns - hsl(300,50.00%,50.00%)
```

## The result after solving this issue, should be a working function taking `hex code` as the input & returning hex complimentary color code of it, as an output:

```js
console.log(Random.complimentaryColor("#ff00ff"));
// returns - #00ff00
```

**Comment by Butzti** [comment]
Hey,
I would like to work on this issue. Can you maybe assign it to me?

**Comment by AnshSinghSonkhia** [comment]
Okay, go for it @Butzti 🚀

**Comment by AnshSinghSonkhia** [comment]
A Stable version code has been pushed. Now, you can fork & star the repo @Butzti :)

**Comment by Butzti** [comment]
I have implemented the feature and created a Pull Request. 👍
